### ISSUE TITLE
bug/ARV-2: Codestyle

### ISSUE THREAD

**Issue by dlyzo** [StanislaWka/Adapriv-response-verstka#2]
![image](https://user-images.githubusercontent.com/9084319/144726303-7a30f5cc-c1cd-4e7d-bb1d-5ee5470f9199.png)

1. Brackets should be on the same line, this is not a C-type language
2. Lines of code should not be that long

Consider using linter for you IDE

**Comment by StanislaWka** [comment]
Fixed

**Comment by StanislaWka** [comment]
Fixed
